---
version: '3.2'
services:
  build-war:
    build: ./builder
    volumes:
      - type: volume
        source: war
        target: /app42/target

  web:
    image: tomcat:6.0.53
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'db42'
      MYSQL_USER: "root"
      MYSQL_PASSWORD: 'secret'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  war:
