---
version: '3'
services:
  build-war:
    build: ./builder
    volumes:
      - type: volume
        source: war
        target: /app42/target

  web:
    image: tomcat:7
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db
      - build-war
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql


volumes:
  war:


