---
version: '3.2'
services:
  build-war:
    build: ./builder
    volumes:
      - type: volume
        source: war
        target: /app42/target

  web:
    image: tomcat:7
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db
      - build-war

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: ap42
        MYSQL_USER: root
        MYSQL_PASSWORD: secret

volumes:
  war:
