---
version: '3.2'
services:
  build-war:
    build: ./builder
    volumes:
      - type: volume
        source: war
        target: /App42PaaS-Java-MySQL-Sample/target

  web:
    image: tomcat:9
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "8514:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  war:
