---
version: '3.2'
services:
  builder:
    build: ./builder
    volumes:
     - war:/app42/target

  web:
    image: tomcat:7-jre8-alpine
    volumes:
     - war:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db42

    volumes:
      - ./mysql:/var/lib/mysql


volumes:
  war:


