---
version: '3.2'
services:
  builder:
    build: ./builder
    volumes:
     - type: vplume
       source: war
       target: /app42/target

  web:
    image: tomcat:jdk8-alpine
    volumes:
     - type: volume
       source: war
       target: /usr/local/tomcat/webapps
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app42

    volumes:
      - ./mysql:/var/lib/mysql


volumes:
  war:


